[tox]
envlist =
    py{38,39}-dj32,
    py{38,39,310,311,312}-dj42,
    py{310,311,312}-dj{50,51},
    py{310,311,312,313,314}-dj52,
    isort,lint

[testenv]
commands =
    coverage run {envbindir}/django-admin test -v2 {posargs:tests}
    coverage xml

usedevelop = true

setenv =
    PYTHONPATH = {toxinidir}
    PYTHONDONTWRITEBYTECODE=1
    DJANGO_SETTINGS_MODULE=tests.test_settings

deps =
    djangorestframework
    model_bakery
    coverage
    coreapi
    coreschema
    drf-spectacular
    drf-yasg
    dj32: Django>=3.2,<4.0
    dj42: Django>=4.2,<5.0
    dj50: Django>=5.0,<5.1
    dj51: Django>=5.1,<5.2
    dj52: Django>=5.2,<5.3
    -r requirements.txt

[testenv:isort]
commands = isort --check-only --diff djfilters tests {posargs}
deps = isort

[testenv:lint]
commands = flake8 djfilters tests {posargs}
deps = flake8

[flake8]
max-line-length = 160

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
